// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnStatus() {
  return window['go']['main']['App']['GetConnStatus']();
}

export function GetGameflowState(arg1) {
  return window['go']['main']['App']['GetGameflowState'](arg1);
}

export function GetMatchAsset(arg1, arg2) {
  return window['go']['main']['App']['GetMatchAsset'](arg1, arg2);
}

export function GetMatchDetail(arg1, arg2) {
  return window['go']['main']['App']['GetMatchDetail'](arg1, arg2);
}

export function GetMatches(arg1, arg2) {
  return window['go']['main']['App']['GetMatches'](arg1, arg2);
}

export function GetPlayersRanked(arg1) {
  return window['go']['main']['App']['GetPlayersRanked'](arg1);
}

export function GetSelfSummoner() {
  return window['go']['main']['App']['GetSelfSummoner']();
}

export function SearchSummoner(arg1) {
  return window['go']['main']['App']['SearchSummoner'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
