// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {lcu} from '../models';
import {gameinfo} from '../models';
import {history} from '../models';
import {parser} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetConnStatus():Promise<lcu.ConnStatus>;

export function GetGameflowState(arg1:Array<number>):Promise<gameinfo.ViewState>;

export function GetMatchAsset(arg1:string,arg2:number):Promise<history.AssetResult>;

export function GetMatchDetail(arg1:number,arg2:string):Promise<parser.MatchDetail>;

export function GetMatches(arg1:string,arg2:number):Promise<history.MatchPage>;

export function GetPlayersRanked(arg1:Array<string>):Promise<Array<history.RankedInfo>>;

export function GetSelfSummoner():Promise<history.SummonerResult>;

export function SearchSummoner(arg1:string):Promise<history.SummonerResult>;

export function SetConfig(arg1:config.Config):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
